name: Merge renovate PRs
on:
  push:
    paths:
      - '.github/workflows/merge.yml'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: merge
  cancel-in-progress: true

jobs:
  find-prs:
    runs-on: ubuntu-latest

    outputs:
      prs: ${{ steps.find-prs.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Find PRs
        id: find-prs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: `owner:${context.repo.owner} is:pr is:open label:"dependencies"`,
              sort: 'created'
            })

            core.info(`Found ${data.total_count} PRs`)

            const prs = data.items.map(item => {
              return {
                repo: item.repository_url.replace('https://api.github.com/repos/', ''),
                number: item.number
              }
            })

            return prs

  merge-prs:
    runs-on: ubuntu-latest
    needs:
      - find-prs

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Merge PRs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
        with:
          github-token: ${{ secrets.GH_OWNER_TOKEN }}
          script: |
            const prs = ${{ needs.find-prs.outputs.prs }}

            for (const pr of prs) {
              core.startGroup(`${pr.repo}#${pr.number}`)

              await exec.exec('gh', ['pr', `-R "${pr.repo}"`, 'merge', `${pr.number}`, '--admin', '--squash', '--delete-branch']);

              core.info(`Merged PR #${pr.number}`)

              core.endGroup()
            }

