name: merge
on:
  push:
    paths:
      - '.github/workflows/merge.yml'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: merge
  cancel-in-progress: false

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Merge PRs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
          TARGET: ${{ github.repository_owner }}
        with:
          script: |
            const script = require('.github/scripts/merge');

            await script({ core, github, exec })
