name: Validate renovate.yaml
on:
  pull_request:
    paths:
      - default.json
  push:
    paths:
      - default.json
  schedule:
    - cron: '0 0 * * 6,0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: latest
      - run: npm install -g renovate
      - run: renovate-config-validator default.json
