name: Validate renovate.yaml
on:
  pull_request:
    paths:
      - default.json
  push:
    paths:
      - default.json
  schedule:
    - cron: '0 0 * * 6,0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: latest
      - run: npm install -g renovate
      - run: renovate-config-validator default.json
